import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'swiper/css';
import 'swiper/css/pagination';
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Providers from "@/Providers";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>
      <Providers>
          <Navbar />
        <main>{children}</main>
        <Toaster />
        {/* footer */}
      </Providers>
      </body>
    </html>
  );
}
